# Generated by Django 4.1.4 on 2023-06-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_societytype_typecode_alter_application_disposaldate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.district",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.state",
            ),
        ),
        migrations.AlterField(
            model_name="society",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.district",
            ),
        ),
        migrations.AlterField(
            model_name="society",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.state",
            ),
        ),
    ]
