# Generated by Django 4.1.4 on 2023-06-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_bank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Liquidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("societyName", models.CharField(max_length=500)),
                (
                    "nameOfLiquidator",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("appoinmentDate", models.DateField(blank=True, null=True)),
                ("validityDate", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.state",
                    ),
                ),
            ],
        ),
    ]
